//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaModelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public Habitacion()
        {
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int IdHabitacion { get; set; }
        public int IdUsuario { get; set; }
        public int NumeroHabitacion { get; set; }
        public Nullable<decimal> PrecioHabitacion { get; set; }
        public int Estatus { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
