//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaModelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAdm
    {
        public int IdLoginAdm { get; set; }
        public int IdRestaurante { get; set; }
        public System.DateTime FechaHora { get; set; }
    
        public virtual Restaurantes Restaurantes { get; set; }
    }
}
