//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaModelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int IdPedido { get; set; }
        public int IdPlatillo { get; set; }
        public int IdHabitacion { get; set; }
        public string Detalles { get; set; }
        public int Estatus { get; set; }
    
        public virtual Habitacion Habitacion { get; set; }
        public virtual Platillos Platillos { get; set; }
    }
}
