//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaModelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platillos
    {
        public Platillos()
        {
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int IdPlatillo { get; set; }
        public int IdRestaurante { get; set; }
        public int IdHabitacion { get; set; }
        public string NombrePlatillo { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int Estatus { get; set; }
    
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual Restaurantes Restaurantes { get; set; }
    }
}
