//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaModelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurantes
    {
        public Restaurantes()
        {
            this.LoginAdm = new HashSet<LoginAdm>();
            this.Platillos = new HashSet<Platillos>();
        }
    
        public int IdRestaurante { get; set; }
        public string Nombre { get; set; }
        public string Contrasena { get; set; }
        public string Descripcion { get; set; }
        public int Puesto { get; set; }
        public int Estatus { get; set; }
    
        public virtual ICollection<LoginAdm> LoginAdm { get; set; }
        public virtual ICollection<Platillos> Platillos { get; set; }
    }
}
