//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaModelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Habitacion = new HashSet<Habitacion>();
            this.Login = new HashSet<Login>();
        }
    
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Contrasena { get; set; }
        public string Apellidos { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string CorreoElectronico { get; set; }
        public int Estatus { get; set; }
    
        public virtual ICollection<Habitacion> Habitacion { get; set; }
        public virtual ICollection<Login> Login { get; set; }
    }
}
